#!/bin/bash

set -e
if [ ! -d "vendor" ]
then
	echo "Install dependencies by composer install"
	composer install
fi

echo "Clear cache configuration"
php artisan config:clear

echo "Configuration Caching"
php artisan config:cache

echo "Run migration"
php artisan migrate --force

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
