version: 0.2

phases:
  pre_build:
    commands:

  build:
    commands:
      # Build your application
      #- aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 372788022554.dkr.ecr.us-west-2.amazonaws.com
      - ls -al
      - cp -rf codebuild/.env.prod src/.env
      - cp -rf codebuild/ec2/scripts scripts
      - cp -rf codedeploy/appspec.yml appspec.yml
      - ls -al
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
    - '.env'
    - 'appspec.yml'
    - 'scripts/'